/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 dna.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/dna.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.038, 0, -0.183]} scale={0.01}>
        <mesh geometry={nodes.Mesh001.geometry} material={materials['_atom_09(quads)_3']} />
        <mesh geometry={nodes.Mesh001_1.geometry} material={materials['_atom_09(quads)_2']} />
        <mesh geometry={nodes.Mesh001_2.geometry} material={materials['_atom_09(quads)_1']} />
      </group>
    </group>
  )
}

useGLTF.preload('/dna.glb')
