/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 intor.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/intor.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Shape1" geometry={nodes.Shape1.geometry} material={materials['15 - Default']} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0} />
      </group>
    </group>
  )
}

useGLTF.preload('/intor.glb')
